### ISSUE TITLE
 Clothes are invisible to others

### ISSUE THREAD

**Issue by R3DIANCE** [lJohhnyl/Corso-RolePlay-GT-MP-#3]

**Comment by ynhhoJ** [comment]
U can make a screen?

**Comment by LeakzLP** [comment]
me too 
http://www.bilder-upload.eu/show.php?file=9b2520-1517252488.png

when one has created a character he comes invisibly to the world only the name can be seen

**Comment by ynhhoJ** [comment]
@LeakzLP , u can make a screen?

**Comment by R3DIANCE** [comment]
![9b2520-1517252488](https://user-images.githubusercontent.com/13523121/35640385-aac880c4-06c5-11e8-8596-4758065454b3.png)

**Comment by eodclan** [comment]
When will the error be eliminated?

**Comment by ynhhoJ** [comment]
@eodclan ,Coming soon...

**Comment by eodclan** [comment]
When will the update come?

**Comment by ynhhoJ** [comment]
@eodclan , 24/25.02.2018.

**Comment by LeakzLP** [comment]
comes the fix 25.02.2018 ?

**Comment by ynhhoJ** [comment]
@LeakzLP , nope. Sorry.

**Comment by ynhhoJ** [comment]
Check the latest update and post if the problem is resolved.

**Comment by LeakzLP** [comment]
resolved!
